name: Release

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create zip archive
        run: |
          mkdir -p release
          zip -r release/release.zip script README.md

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: scripts
          path: release/release.zip
